col_patr_bat = {
    "nodeId": "node_id",
    "typeObject": "type_object",
    "hasChildren": "has_children",
    "text": "text",
    "info": "info",
    "isGhost": "is_ghost",
    "ghostId": "ghost_id",
    "isTrueGhost": "is_true_ghost",
    "isMeter": "is_meter",
    "hasComponents": "has_components",
    "isDepreciated": "deprecie",
    "depreciatedDate": "deprecie_date",
    "supervisor": "superviseur",
    "icon": "icon",
    "Reference": "reference",
    "Name": "name",
    "Invariant": "invariant",
    "Purpose": "purpose",
    "IsPublicDomain": "is_public_domain",
    "WeatherStation": "weather_station",
    "Address": "adresse",
    "PostalCode": "code_postal",
    "Town": "commune",
    "Country": "pays",
    "Altitude": "altitude",
    "IsDepreciated": "deprecie_txt", # DOUBLON
    "DepreciatedDate": "deprecie_date_2", # DOUBLON
    "MeteoCorrectorHeat": "meteo_corrector_heat",
    "MeteoCorrectorCold": "meteo_corrector_cold",
    "ConstructionYear": "construction_year",
    "NumberOfFloorPos": "number_of_floors_pos",
    "NumberOfFloorNeg": "number_of_floors_neg",
    "AvailableHeightClearance": "available_height_clearance",
    "BuildingPABType": "building_pab_type",
    "CategoryPAB": "category_pab",
    "NumLastBuildingPermit": "num_last_building_permit",
    "DateLastBuildingPermit": "date_last_building_permit",
    "IsTertiaryDecree": "is_tertiary_decree",
    "OperatEFA": "operat_efa",
    "GradeSubjection": "grade_subjection",
    "CaseSubjection": "case_subjection",
    "SIRET": "siret",
    "IUBPrefix": "iub_prefix",
    "IUBSection": "iub_section",
    "IUBPlot": "iub_plot",
    "IUBBuilding": "iub_building",
    "IUBLot": "iub_lot",
    "ArchitecturalEnergyEfficiency": "architectural_energy_efficiency",
    "WinterComfort": "winter_comfort",
    "SummerComfort": "summer_comfort",
    "ConstructionValue": "construction_value",
    "PurchaseValue": "purchase_value",
    "RentalValue": "rental_value",
    "BuildingLease": "building_lease",
    "EmphyteuticLease": "emphyteutic_lease",
    "Coproperty": "copropriete",
    "OccupancyAgreement": "occupancy_agreement",
    "MaintenanceAgreement": "maintenance_agreement",
    "ServiceManager": "service_manager",
    "RelevantCommission": "relevant_commission",
    "Location": "adresse_complete",
    "Remark": "remarque",
    "SHON": "shon",
    "Surface chauffée": "surface_chauffee",
    "SHOB": "shob",
    "Surface RT": "surface_rt",
    "Surface utile": "surface_utile",
    "Surface foncière": "surface_fonciere",
    "Suface d'emprise au sol": "surface_emprise_sol",
    "Surface de plancher": "surface_plancher",
    "Volume": "volume",
    "Capacité d'accueil": "capacite_accueil",
    "Fréquentation": "frequentation",
    "Surface de bassin": "surface_bassin",
    "Nombre de repas": "nombre_repas"
}

col_patr = {
    "nodeId": "node_id",
    "typeObject": "type_object",
    "hasChildren": "has_children",
    "text": "text",
    "info": "info",
    "isGhost": "is_ghost",
    "ghostId": "ghost_id",
    "isTrueGhost": "is_true_ghost",
    "isMeter": "is_meter",
    "hasComponents": "has_components",
    "isDepreciated": "deprecie",
    "depreciatedDate": "deprecie_date",
    "supervisor": "superviseur",
    "icon": "icon",
    "Name": "name",
    "Age": "age",
    "Expendables": "expendables",
    "InvoicingType": "invoicing_type",
    "Reference": "reference",
    "SupplyPointNumber": "supply_point_number",
    "RAEPCENumber": "numero_rae_pce",
    "Invariant": "invariant",
    "InstallationDate": "installation_date",
    "ContractNumber": "contact_number",
    "PurchasingGroup": "purchasing_group",
    "Access": "access",
    "Connection": "connection",
    "Category": "category",
    "Owner": "owner",
    "SubscriptionHolder": "subscription_holder",
    "PayingInvoice": "paying_invoice",
    "NetworkManager": "network_manager",
    "StatementSupplier": "statement_supplier",
    "ContractTerm": "contract_term",
    "ImpulseMeter": "impulse_meter",
    "StatementClient": "statement_client",
    "Location": "adresse_complete",
    "Brand": "marque",
    "Model": "modele",
    "OutputInformation": "output_information",
    "TypeOutputInformation": "type_output_information",
    "WeightPulse": "weight_pulse",
    "Provider": "fournisseur",
    "Contract": "contrat",
    "Tariff": "tarif",
    "Address": "adresse",
    "PostalCode": "code_postal",
    "Town": "commune",
    "Country": "pays",
    "IsDepreciated": "deprecie_txt", # DOUBLON
    "DepreciatedDate": "deprecie_date_2", # DOUBLON
    "ManualStatement": "manual_statement",
    "AdditionalEqpt": "additional_eqpt",
    "TariffCode": "tarif_code",
    "SubcribedOrReducedPower": "puissance_souscrite_reduite",
    "Latitude": "latitude",
    "Longitude": "longitude",
    "Remark": "remarque",
    "HasUseReactiveEnergy": "has_use_reactive_energy",
    "IsCostSPDependency": "is_cost_sp_dependency",
    "TotalInstalledPower": "total_installed_power",
    "TypeOfInstallation": "type_installation",
    "HasSalesAgreement": "has_sales_agreement",
    "ContractHolder": "contract_holder",
    "NumberInverters": "nombre_onduleur",
    "PowerByInverter": "puissance_par_onduleur",
    "CellTechnology": "cell_technology",
    "PanelTechnology": "panel_technology",
    "TypeIntegration": "type_integration",
    "InstalledArea": "surface_installee",
    "AnnualTheoricProd": "production_theorique_annuelle",
    "FareSegment": "fare_segment",
    "VoltageDomain": "voltage_domain",
    "Temporality": "temporalite"
}

col_patr_site = {
    "nodeId": "node_id",
    "typeObject": "type_object",
    "hasChildren": "has_children",
    "text": "text",
    "info": "info",
    "isGhost": "is_ghost",
    "ghostId": "ghost_id",
    "isTrueGhost": "is_true_ghost",
    "isMeter": "is_meter",
    "hasComponents": "has_components",
    "isDepreciated": "deprecie",
    "depreciatedDate": "deprecie_date",
    "supervisor": "superviseur",
    "icon": "icon",
    "Reference": "reference",
    "Name": "name",
    "Invariant": "invariant",
    "Purpose": "purpose",
    "IsPublicDomain": "is_public_domain",
    "IsTertiaryDecree": "is_tertiary_decree",
    "WeatherStation": "weather_station",
    "Address": "adresse",
    "PostalCode": "code_postal",
    "Town": "commune",
    "Country": "pays",
    "Altitude": "altitude",
    "IsDepreciated": "deprecie_txt", # DOUBLON
    "DepreciatedDate": "deprecie_date_2", # DOUBLON
    "BuildingLease": "building_lease",
    "EmphyteuticLease": "emphyteutic_lease",
    "Coproperty": "copropriete",
    "OccupancyAgreement": "occupancy_agreement",
    "MaintenanceAgreement": "maintenance_agreement",
    "ServiceManager": "service_manager",
    "RelevantComission": "relevant_comission",
    "ChargingZoneGas": "charging_zone_gaz",
    "ClimateArea": "climate_area",
    "MeteoCorrectorHeat": "meteo_corrector_heat",
    "MeteoCorrectorCold": "meteo_corrector_cold",
    "OperatEFA": "operat_efa",
    "GradeSubjection": "grade_subjection",
    "CaseSubjection": "case_subjection",
    "SIRET": "siret",
    "IUBPrefix": "iub_prefix",
    "IUBSection": "iub_section",
    "IUBPlot": "iub_plot",
    "IUBBuilding": "iub_building",
    "IUBLot": "iub_lot",
    "CadastralReferences": "references_cadastrales",
    "BuildingCount": "nombre_batiments",
    "HasResidentialSchool": "has_residential_school",
    "HasShed": "has_shed",
    "WoodEnergyPotential": "wood_energy_potential",
    "SolarPhotovoltaicPotential": "solar_photovoltaic_potential",
    "GeothermalPotential": "geothermal_potential",
    "SolarThermalPotential": "solar_thermal_potential",
    "Location": "adresse_complete",
    "Remark": "remarque",
    "SHON": "shon",
    "Surface chauffée": "surface_chauffee",
    "SHOB": "shob",
    "Surface RT": "surface_rt",
    "Surface utile": "surface_utile",
    "Surface foncière": "surface_fonciere",
    "Suface d'emprise au sol": "surface_emprise_sol",
    "Surface de plancher": "surface_plancher",
    "Volume": "volume",
    "Capacité d'accueil": "capacite_accueil",
    "Fréquentation": "frequentation",
    "Surface de bassin": "surface_bassin",
    "Nombre de repas": "nombre_repas",
}

col_synthesis = {
    "Type": "type",
    "Tarif": "tarif",
    "Invariant": "invariant",
    "Nom": "nom",
    "Adresse": "adresse",
    "Ville": "ville",
    "NumeroPDL": "numero_pdl",
    "Raepce": "raepce",
    "Energie": "energie",
    "NumeroContrat": "numero_contrat",
    "Fournisseur": "fournisseur",
    "CodeTarif": "code_tarif",
    "PuissanceSouscriteOuReduite": "puissance_souscrite_reduite",
    "Mois": "mois",
    "Annee": "annee",
    "Consommation": "consommation",
    "ConsoUnite": "conso_unite",
    "EnergieFinale_kWhEFFact": "energie_finale_kwh_eff",
    "EnergiePrimaire_kWhEP": "energie_primaire_kwh_ep",
    "Co2_kg": "co2_kg",
    "CoutTTC": "cout_ttc",
    "Depassement": "deplacement"
}
